---
- name: LXC set core.https_address
  shell: "lxc config set core.https_address {{ lxd_api_address }}:{{ lxd_api_port }}"

- name: LXC set trust-password
  shell: "lxc config set core.trust_password {{ lxd_api_password }}"
  no_log: true

- name: setting default profile
  lxd_profile:
    name: default
    state: present
    config: "{{ lxd_default_profile_config }}"
    devices: "{{ lxd_default_profile_devices }}"

- name: Generate lxd virbr0 network config file
  copy: 
    content: "{{ lxc_network_virbr0_config }}"
    dest: "/tmp/lxc_network_{{ lxd_subnet_interface }}"

- name: setting default network
  shell: "lxc network show {{ lxd_subnet_interface }} || lxc network create {{ lxd_subnet_interface }}"

- name: setting default network
  shell: "cat /tmp/lxc_network_{{ lxd_subnet_interface }} | lxc network edit {{ lxd_subnet_interface }}"

#- name: Delete generated virbr0 network config file
#  file:
#    path: /tmp/lxc_network_{{ lxd_subnet_interface }}
#    state: absent

- name: Stop dnsmasq@virbr0
  systemd:
    name: "dnsmasq@{{ lxd_subnet_interface }}"
    state: stopped
    enabled: false
  ignore_errors: true

- name: Delete old network/intefaces file 
  file:
    path: /etc/network/interfaces.d/virbr0.conf
    state: absent

- name: Check if interfaces.d is enabled
  lineinfile: 
    dest: /etc/network/interfaces
    line: 'source /etc/network/interfaces.d/*'
    state: present

