---
- name: Get network-address
  shell: "lxc info | grep core.https_address | cut -c24- | sed 's/.$//g'"
  register: __lxd_info_http_addr

- debug: "msg={{ __lxd_info_http_addr.stdout | trim }}"
- debug: "var=lxd_api_address"
- name: Exec lxd init
  shell: "lxd init --auto --network-address='{{ lxd_api_address }}' --network-port={{ lxd_api_port }} --storage-backend=dir --trust-password='{{ lxd_api_password }}'"
  when: "__lxd_info_http_addr.stdout | trim != lxd_api_address ~ ':' ~ lxd_api_port"

- name: disable and stop lxd-bridge
  systemd: state=stopped name=lxd-bridge enabled=false

- name: disable lxd-bridge in config
  lineinfile: 'dest=/etc/default/lxd-bridge regexp=^USE_LXD_BRIDGE line=USE_LXD_BRIDGE="false"'

- name: setting default profile
  lxd_profile:
    name: default
    state: present
    config: "{{ lxd_default_profile_config }}"
    devices:
      eth0:
        nictype: bridged
        parent: virbr0
        type: nic

- name: Check if interfaces.d is enabled
  lineinfile: 
    dest: /etc/network/interfaces
    line: 'source /etc/network/interfaces.d/*'
    state: present

- name: Create lxd interface in network/interfaces
  template:
    src: lxd_iface.conf.j2
    dest: /etc/network/interfaces.d/{{ lxd_subnet_interface }}.conf
    mode: 0655

- name: "ifup interfaces"
  command: "ifup {{ lxd_subnet_interface }}"
  when: "lxd_subnet_interface not in ansible_interfaces"

