---
- name: Install stable repo
  apt_repository:
    repo: 'ppa:ubuntu-lxc/lxd-stable'
    state: absent

- name: apt install lxd and bridge-utils
  apt: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
    default_release: "{{ ansible_distribution_release }}-backports"
  with_items:
    - lxd
    - lxd-client
    - bridge-utils
